# Generated by Django 4.0 on 2022-09-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tododata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('todo', models.CharField(max_length=50)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
